# Generated by Django 4.2.20 on 2025-04-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_range", models.CharField(max_length=20, unique=True)),
                ("active_user_count", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityEventLog",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("date", models.DateField()),
                ("tags", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.TextField(unique=True)),
                ("mentions", models.IntegerField(default=0)),
                ("wishlist_count", models.IntegerField(default=0)),
                ("is_hot", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("nickname", models.TextField()),
                ("total_messages", models.IntegerField(default=0)),
                ("positive_score", models.IntegerField(default=0)),
                ("negative_score", models.IntegerField(default=0)),
                ("activity_level", models.CharField(max_length=1)),
                ("tags", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sentiment", models.CharField(max_length=10)),
                ("keyword_match", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="triplinebot.userprofile",
                    ),
                ),
            ],
        ),
    ]
